import {Injectable} from '@angular/core';

@Injectable()
export class DocentesService{
    getDocentes(): string[]{
        return[
            //ingeneria de sistemas
            'Blanco Garrido Fabian',
            'Torres Ceron Wilfred',
            'Alonso Moncada Mauricio Antonio',
            'Samaca Chavarriaga Luis Abdul',
            'Velasquez Carranza Juan Fernando',
            'Simanca Herrera Fredys Alberto',
            'Ojeda Perez Jorge Eliecer',
            'Novoa Torres Norberto',
            'Forero Saboya Pedro Alonso',
            'Carreño Hernandez Pablo Enrrique',
            'Gaitan Gomez Henry',
            'Acosta Rodriguez Rafael Antonio',
            'Reyes Roncancio Fredy',
            'Mellizo Angulo Oscar Guillermo',

            //ingeneria de industrial
            'Cubaque Mendoza Ramon Maria',
            'Meza Torres Ricardo Efren',
            'Guarin Salinas Andres Giovanni',
            'Duarte Forero Edgar Leonardo',
            'Fonseca Burgos Francisco Javier',
            'Fuentes Rojas Ever Angel',
            'Alarcon William',
            'Paramo Macias Irma Teresa',
            'Laguna Maldonado Libardo',
            'Ochoa Rodriguez Julio Fernando',
            'Forero Mayorga Luis',
            'Salcedo Rodriguez Peregrino',
            'Campos Naranjo Jose Ignacio',
            'Valero Cabezas Jose Reine',
            'Barbeo Morales Jorge Enrique',
            'Robles Sandoval Juan Gabriel',
            'Rodriguez Arevalo Ignacio ALberto',
            'De Antonio Suarez Orlando',
            'Rey Baquero Gilberto',
            'Guarin Slainas Andres Giovanni',
            'Meneses Velosa Sonia Lucia',
            'Valero Cabezas Jose Rene',
            'Camacho Oliveros Manuel Angel',
            'Guerrero Salas Humberto',
            'Santiago Garzon Juan Carlos',
            'Gonzales Becerra Fernando',
            'Castro Piñeres Hernando',
            'Ramirez Castañeda Leyla Nayibe',
            'Zuleta Zuleta Jorge Enrique',
            'Castro Ramirez Omeiro',
            'Saavedra Torres Martha Rocio',
            'Saenz Blanco Fabiola',
            'Mayorga Morato Manuel ALfonso',
            'Muñoz Artunduaga Nora Lucy',
            'Peña Carreño Jhon Albeyro',

            //Nucleo Comun
            'Gonzalez Hernandez Dory Luz',
            'Velasquez Giraldo Jose Rodrigo',
            'Sanchez Rodriguez Martha Cecilia',
            'Niño Salamanca Jesus',
            'Cuesta Alfaro Jonathan',
            'Mendez Lara Jeisson Steven',
            'Bulla Pereira Edwin Alberto',
            'Aguirre Gomez Fredy Alexander',
            'Garcia Gonzalez Sara',
            'Garavito Tellez Sara Ines',
            'Lopez Castro Cesar Augusto',
            'Bolaños Gallo Jaime',
            'Novoa Galeano Martha Alix',
            'Acevedo Buitrago Baudilio',
            'Castro Vargas Henry Isaac',
            'Carrillo Cruz Carlos Enrique',
            'Guevara Chacon Luz Mery',
            'Davila Rubio Alejandro Mauricio',
            'Gomez Rios Arley Ramses',
            'Garcia Gonzalez Sara',
            'Forero Roncancio German Eduardo',
            'Bolaños Gallo Jaime',
            'Sierra Barrero Jairo Ernesto',
            'Zapata Peña Jair',
            'Plaza Riaño Carlos Andres',
            'Miguez Pulido Alvaro',
            'Zorro Mateus Patricia pamela',
            'David Otalvaro Maria Isable',
            'Herrera  Paloma Myriam',
            'Lemus Alarcon Jose Benigno',
            'Arce Narvaez Gloria Cristina',
            'Perez Palomino Fernando',
            'Goez Theran Cristin Alberto',
            'Rivera Cardenas Guiovanna'

        ];
    }
}

